server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website-resources
    username: root
    password: R00t1@$$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect