kafka:
  bootstrapAddress: http://localhost:9092
server:
  servlet:
    context-path: /website-resources
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:liquibase-changelog/liquibase-changelog.yaml