kafka:
  bootstrapAddress: http://localhost:9092
server:
  port: 9000
  servlet:
    context-path: /website-resources
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:website-resources
    username: user
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:liquibase-changelog/liquibase-changelog.yaml